[package]
name = "food-frontend"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
maud = { version = "0.27.0", features = ["axum"]}
tokio.workspace = true

[lints]
workspace = true
